name: Build

on:
  create:
  pull_request:
    branches:
      - main

jobs:
  branch-naming-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Branch name policy check
        if: |
          github.ref_type == 'branch'
          && (contains(github.ref,'release') || (github.event.pull_request.head.ref != '' && contains(github.event.pull_request.head.ref,'release')))
        run: echo 'Branch name contains release pattern:' ${{github.ref}} ${{github.event.pull_request.head.ref}} ${{github.ref_type}} && exit 1

      - name: Build
        run: echo 'Built image'
     
