name: Branch Naming Policy Action

on:
  create:
  delete:
  pull_request:
    branches:
      - main

jobs:
  branch-naming-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Branch Name For Release
        if: (github.ref_type == 'branch' || github.ref_type == 'pull_request') && ${{startsWith(github.ref,'/refs/heads/release-v.') == true}}
        run: echo 'Branch name contains release pattern:' ${{github.ref}} && exit 1
