name: Branch Naming Policy Action

on:
  create:
  pull_request:
    branches:
      - main

jobs:
  branch-naming-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Log
        run: echo ${{github.ref}} ${{github.event.pull_request.head.ref}} ${{github.ref_type}} ${{github.ref_type == 'branch'}} ${{contains('release',github.ref) == true}} ${{contains('release',github.event.pull_request.head.ref) == true}} 

      - name: Check Branch Name For Release
        if: |
          github.ref_type == 'branch'
          && (contains('release',github.ref) == true || contains('release',github.event.pull_request.head.ref) == true)
        run: echo 'Branch name contains release pattern:' ${{github.ref}} ${{github.event.pull_request.head.ref}} ${{github.ref_type}} && exit 1
