name: Branch Naming Policy Action

on:
  create:
  pull_request:
    branches:
      - main

jobs:
  branch-naming-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Branch Name For Release
        # if: |
        #   (github.ref_type == 'branch' && startsWith(github.ref,'refs/heads/release') == true)
        #   || (github.ref_type == 'pull_request' && startsWith(github.event.pull_request.head.ref,'refs/heads/release') == true)
        run: echo 'Branch name contains release pattern:' ${{github.ref}} ${{github.event.pull_request.head.ref}} && exit 1
